<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SpaRoot>..\detailedcountries.client</SpaRoot>
    <SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:61230</SpaProxyServerUrl>
    <UserSecretsId>608759e6-812a-47aa-8fe7-fc90e18944c4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\browser\favicon.ico" />
    <Content Remove="wwwroot\browser\index.html" />
    <Content Remove="wwwroot\browser\main-YJRSYYJQ.js" />
    <Content Remove="wwwroot\browser\media\layers-2x-TBM42ERR.png" />
    <Content Remove="wwwroot\browser\media\layers-55W3Q4RM.png" />
    <Content Remove="wwwroot\browser\media\marker-icon-2V3QKKVC.png" />
    <Content Remove="wwwroot\browser\polyfills-FFHMD2TL.js" />
    <Content Remove="wwwroot\browser\styles-JP2SUF7V.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\browser\favicon.ico" />
    <None Include="wwwroot\browser\index.html" />
    <None Include="wwwroot\browser\main-YJRSYYJQ.js" />
    <None Include="wwwroot\browser\media\layers-2x-TBM42ERR.png" />
    <None Include="wwwroot\browser\media\layers-55W3Q4RM.png" />
    <None Include="wwwroot\browser\media\marker-icon-2V3QKKVC.png" />
    <None Include="wwwroot\browser\polyfills-FFHMD2TL.js" />
    <None Include="wwwroot\browser\styles-JP2SUF7V.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>8.*-*</Version>
    </PackageReference>
    <PackageReference Include="MongoDB.Driver" Version="3.7.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\detailedcountries.client\DetailedCountries.Client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

</Project>
